In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [2]:
# QUESTIONS:
#/* Q10: Produce a list of facilities with a total revenue less than 1000.
#The output of facility name and total revenue, sorted by revenue. Remember
#that there's a different cost for guests and members! */

def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT a.name, a.revenue
FROM 
(SELECT name, 
SUM(CASE WHEN memid !=0 THEN membercost * slots 
     WHEN memid = 0 THEN guestcost * slots
     END) AS revenue 
FROM Bookings
INNER JOIN Facilities 
USING (facid) 
GROUP BY name) AS a
WHERE a.revenue < 1000
ORDER BY a.revenue DESC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

In [3]:
#/* Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order */

def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT a.surname, a.firstname, (m.firstname || ' ' || m.surname) AS recommended_by
FROM 
(SELECT memid, firstname, surname, recommendedby 
FROM Members 
WHERE recommendedby !=0) AS a
INNER JOIN Members as m
ON a.recommendedby = m.memid 
ORDER BY a.surname, a.firstname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 'Ponder Stibbons')
('Baker', 'Anne', 'Ponder Stibbons')
('Baker', 'Timothy', 'Jemima Farrell')
('Boothe', 'Tim', 'Tim Rownam')
('Butters', 'Gerald', 'Darren Smith')
('Coplin', 'Joan', 'Timothy Baker')
('Crumpet', 'Erica', 'Tracy Smith')
('Dare', 'Nancy', 'Janice Joplette')
('Genting', 'Matthew', 'Gerald Butters')
('Hunt', 'John', 'Millicent Purview')
('Jones', 'David', 'Janice Joplette')
('Jones', 'Douglas', 'David Jones')
('Joplette', 'Janice', 'Darren Smith')
('Mackenzie', 'Anna', 'Darren Smith')
('Owen', 'Charles', 'Darren Smith')
('Pinker', 'David', 'Jemima Farrell')
('Purview', 'Millicent', 'Tracy Smith')
('Rumney', 'Henrietta', 'Matthew Genting')
('Sarwin', 'Ramnaresh', 'Florence Bader')
('Smith', 'Jack', 'Darren Smith')
('Stibbons', 'Ponder', 'Burton Tracy')
('Worthington-Smyth', 'Henry', 'Tracy Smith')

In [4]:
#/* Q12: Find the facilities with their usage by member, but not guests */

def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT facid, name, COUNT(memid)
FROM Bookings
INNER JOIN Facilities
USING (facid)
WHERE memid !=0 
GROUP BY facid
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 308)
(1, 'Tennis Court 2', 276)
(2, 'Badminton Court', 344)
(3, 'Table Tennis', 385)
(4, 'Massage Room 1', 421)
(5, 'Massage Room 2', 27)
(6, 'Squash Court', 195)
(7, 'Snooker Table', 421)
(8, 'Pool Table', 783)

In [5]:
#/* Q13: Find the facilities usage by month, but not guests */

def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT 
strftime('%m', starttime) AS month, COUNT(facid) AS total_facilities
FROM Bookings
GROUP BY month
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 658)
('08', 1472)
('09', 1913)